#!/bin/sh

### aliases

## ls to exa
alias ls='exa -F --color=always --group-directories-first'
alias la='exa -aF --color=always --group-directories-first'
alias ll='exa -l --color=always --group-directories-first'
alias lt='exa -aTF --color=always --group-directories-first'
alias lr='exa -aRF --color=always --group-directories-first'

## editor
alias vim='nvim'
alias v='vim'

## pacman
alias sps='sudo pacman -S'
alias pss='sudo pacman -Ss'

## wifi
alias wifilist='nmcli device wifi list'
alias wificonnect='nmcli --ask device wifi connect' 

## doomstuff
alias doomsync="~/.emacs.d/bin/doom sync"
alias doomdoctor="~/.emacs.d/bin/doom doctor"
alias doomupgrade="~/.emacs.d/bin/doom upgrade"
alias doompurge="~/.emacs.d/bin/doom purge"

## git
alias gconf="/usr/bin/git --git-dir=$HOME/repos/devaneyJE/dotfiles --work-tree=$HOME"
alias confadd="gconf add -u ~/.config && gconf status"

##
alias grep="grep --color=auto"
alias diff="diff --color=auto"

alias rm="rm -i"
#alias rmr="rm -ri"
