#! /bin/sh

sxhkd &

mons_check=$(bspc query -M --names)
if [[ $mons_check == *"HDMI-0"* ]];then
	mon_mode="dual"
else
	mon_mode="single"
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# custom
set -U SXHKD_SHELL /bin/bash &

if [[ $mon_mode == "dual" ]]; then
	bspc monitor HDMI-0 -d 1 2 3 4 5
	bspc monitor DP-2 -d 6 7 8 9 0
	exec $HOME/.config/polybar/nord_bspwm/dual/launch.sh
elif [[ $mon_mode == "single" ]]; then
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
	exec $HOME/.config/polybar/nord_bspwm/single/launch.sh
fi
